# Copyright 2021 Gabor Meszaros
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  sip-domain:
    default: "localhost"
    description: Your SIP domain
  external-url:
    type: string
    description: "The hostname of the service to create an ingress for."
  tls-secret-name:
    default: ""
    type: string
    description: "The name of the TLS secret to use. Leaving this empty will configure an ingress with TLS disabled."
